# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claude-code = {
    pname = "claude-code";
    version = "2.1.199";
    src = fetchurl {
      url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/2.1.199/linux-x64/claude";
      sha256 = "sha256-sx39Xj3uI7UcQuDY3bQFFIl4I306q8jLv3fFz4M2fic=";
    };
  };
  codex = {
    pname = "codex";
    version = "0.142.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/@openai/codex/-/codex-0.142.5.tgz";
      sha256 = "sha256-+bPYbxDy15xti3z1r0PJJu0guG5DGPm0MmYaxA06CcE=";
    };
  };
  codex-linux-x64 = {
    pname = "codex-linux-x64";
    version = "0.142.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/@openai/codex/-/codex-0.142.5-linux-x64.tgz";
      sha256 = "sha256-oD4xFssJCa67Az45zUAYs6Ha+dSJYxk5thY/+pB63kc=";
    };
  };
  orca-ide = {
    pname = "orca-ide";
    version = "1.4.120";
    src = fetchurl {
      url = "https://github.com/stablyai/orca/releases/download/v1.4.120/orca-ide_1.4.120_amd64.deb";
      sha256 = "sha256-mXFRviIZoXDDYezeUUrOfeXThCXBvLn4h9bvhrf5mzw=";
    };
  };
  paseo = {
    pname = "paseo";
    version = "0.1.103";
    src = fetchurl {
      url = "https://github.com/getpaseo/paseo/releases/download/v0.1.103/Paseo-0.1.103-amd64.deb";
      sha256 = "sha256-gIzyEK0hqGpnBoBoXQBgmQ5W+WjQaaQHWZtb5BlFTz8=";
    };
  };
}
