# Autostart
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start sunshine.service
exec-once = waybar
exec-once = awww-daemon --no-cache
exec-once = $HOME/.config/hypr/scripts/wallpaper.sh
