$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, SPACE, exec, wofi --show drun
bind = $mainMod, W, killactive,
bind = $mainMod, B, exec, firefox

bind = $mainMod CTRL SHIFT, left, movewindow, l
bind = $mainMod CTRL SHIFT, right, movewindow, r
bind = $mainMod CTRL SHIFT, up, movewindow, u
bind = $mainMod CTRL SHIFT, down, movewindow, d

bind = $mainMod SHIFT, right, resizeactive, 20 0
bind = $mainMod SHIFT, left, resizeactive, -20 0
bind = $mainMod SHIFT, up, resizeactive, 0 -20
bind = $mainMod SHIFT, down, resizeactive, 0 20
