unbind = $mainMod, Q
unbind = $mainMod, R
unbind = $mainMod, D
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $menu

$mainMod = SUPER

unbind = $mainMod, Q
unbind = $mainMod, R
unbind = $mainMod, D
unbind = $mainMod, W
unbind = $mainMod, B

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, W, killactive,
bind = $mainMod, B, exec, firefox

# Move active window
bind = $mainMod CTRL SHIFT, left, movewindow, l
bind = $mainMod CTRL SHIFT, right, movewindow, r
bind = $mainMod CTRL SHIFT, up, movewindow, u
bind = $mainMod CTRL SHIFT, down, movewindow, d

# Resize active window
bind = $mainMod SHIFT, right, resizeactive, 20 0
bind = $mainMod SHIFT, left, resizeactive, -20 0
bind = $mainMod SHIFT, up, resizeactive, 0 -20
bind = $mainMod SHIFT, down, resizeactive, 0 20
