$mainMod = SUPER

unbind = $mainMod, RETURN
unbind = $mainMod, SPACE
unbind = $mainMod, C
unbind = $mainMod, W
unbind = $mainMod, B
unbind = $mainMod, E

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, SPACE, exec, wofi --show drun
bind = $mainMod, W, killactive,
bind = $mainMod, B, exec, google-chrome
bind = $mainMod, E, exec, thunar

bind = $mainMod CTRL, left, movewindow, l
bind = $mainMod CTRL, right, movewindow, r
bind = $mainMod CTRL, up, movewindow, u
bind = $mainMod CTRL, down, movewindow, d

binde = $mainMod SHIFT, right, resizeactive, 20 0
binde = $mainMod SHIFT, left, resizeactive, -20 0
binde = $mainMod SHIFT, up, resizeactive, 0 -20
binde = $mainMod SHIFT, down, resizeactive, 0 20
