monitor=,preferred,auto,1

general:gaps_in = 3
general:gaps_out = 8
general:border_size = 2
general:col.active_border = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
general:col.inactive_border = rgba(414868aa)

decoration:rounding = 8
decoration:rounding_power = 2

input {
    kb_layout = br
    kb_variant = nodeadkeys
    follow_mouse = 1
    sensitivity = 0
    scroll_method = 2fg

    touchpad {
        natural_scroll = true
        tap-to-click = true
        tap-and-drag = true
        drag_lock = false
        clickfinger_behavior = false
        middle_button_emulation = false
        disable_while_typing = true
        scroll_factor = 0.9
    }
}

gestures {
    gesture = 3, horizontal, workspace
    gesture = 3, down, close
    gesture = 3, up, fullscreen, maximize
}
