general {
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = $HOME/nixos-config/wallpapers/comic_original.png
    blur_passes = 3
    blur_size = 7
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 260, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(65, 72, 104)
    inner_color = rgb(36, 40, 59)
    font_color = rgb(192, 202, 245)
    check_color = rgb(122, 162, 247)
    fail_color = rgb(247, 118, 142)
    placeholder_text = <span foreground="##c0caf5">Digite a senha...</span>
    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(192, 202, 245, 1.0)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d de %B")"
    color = rgba(192, 202, 245, 0.8)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(122, 162, 247, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
